version: '3.8'
services:

  
  frondend:
    image: mailinh_frontend/frontend
    container_name: mailinh_frontend
    restart: unless-stopped
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2079:2079"
    volumes:
      - /hthai/jenkins_data/workspace/mailinh-frontend:/frontend


